# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Photo Stunner' do
  pod 'OCMock', '~> 3.1.2'
end

target 'Photo StunnerTests' do
  pod 'OCMock', '~> 3.1.2'
end

